### ISSUE TITLE
vm-replica-2.md の「再起動」の文言について

### ISSUE THREAD

**Issue by RyusukeFujita** [jpaztech/blog#127]
下記の「再起動」というのは不要ではないでしょうか?

> シャットダウン オプションが Shutdown（シャットダウン）再起動となっている必要がありますので

---

#### Document Details

⚠ *Do not edit this section.

* ID: 0872976c-432a-53f6-8187-6113344377e7
* 対象記事: [VM 複製方法について part.2/3 一般化したイメージから VM を複製する手順](https://jpaztech.github.io/blog/vm/vm-replica-2/)
* Content Source: [articles/vm/vm-replica-2.md](https://github.com/jpaztech/blog/blob/master/articles/vm/vm-replica-2.md)
* Author:

**Comment by Yudai-Tomita** [comment]
確かに不要な文字列「再起動」が入ってしまっている状態でしたので、
修正してプルリクエストをいたしました。
ご指摘ありがとうございました。
