### ISSUE TITLE
Azure 環境における Windows Server 2016 にて日本語の言語パック適用ができない

### ISSUE THREAD

**Issue by keizom** [jpaztech/blog#149]
エラーコード0x800f0922の記載がない
役割の追加もできないことの記載がない

**Comment by kiki-kekat** [comment]
checking

**Comment by kiki-kekat** [comment]
フィードバックいただきまして、誠にありがとうございます。
いただきました内容につきまして、追加で公開できる情報があれば反映させていただきますが、特定のエラーやご状況につきましてお困りの状況がございます場合やご不明点がございます場合には、弊社サポートまでお問い合わせくださいますようお願いいたします。
