### ISSUE TITLE
-- が - で表示されてしまう。

### ISSUE THREAD

**Issue by jyama4ta** [jpaztech/blog#211]
コマンドを例示する際、ハイフンが 2 つ連続している場合、Markdown ファイル上は -- になっているが、ブログでは - で表示されてしまっている。
例）下記記事の --blob-type の箇所
https://jpaztech.github.io/blog/vm/create-vm-using-vhd/
https://github.com/jpaztech/blog/blob/master/articles/vm/create-vm-using-vhd.md

**Comment by kiki-kekat** [comment]
記事内にエスケープ文字を追加して対応しました
