### ISSUE TITLE
リンク切れ

### ISSUE THREAD

**Issue by mizuhokitao** [jpaztech/blog#237]
> 言語パックインストール時のご留意点
> https://jpwinsup.github.io/blog/2022/06/17/UserInterfaceAndApps/LanguageSupport_IME/lp-consideration/

上記リンク切れになっておりました。記事のタイトルから、以下のリンクが正しいでしょうか？
https://jpwinsup.github.io/blog/2022/06/22/UserInterfaceAndApps/LanguageSupport_IME/lp-consideration/

---

#### Document Details

⚠ *Do not edit this section.

* ID: d1c3a89c-152b-5686-894a-adb297a89151
* 対象記事: [Azure 環境における Windows Server 2019 の日本語の言語パック適用手順について (修正展開済み)](https://jpaztech.github.io/blog/vm/win2019-jp-lpk/)
* Content Source: [articles/vm/win2019-jp-lpk.md](https://github.com/jpaztech/blog/blob/master/articles/vm/win2019-jp-lpk.md)
* Author:

**Comment by jyama4ta** [comment]
ご指摘いただきありがとうございます。修正いたしました。
