### ISSUE TITLE
generate wrong RSS URL

### ISSUE THREAD

**Issue by tsubasaxZZZ** [jpaztech/blog#3]
When access from RSS reader to blog post, it show 404.
It looks like wrong  RSS URL in atom.xml.

https://jpaztech.github.io/blog/atom.xml

actual: 
https://jpaztech.github.io/network/appgw-troubleshooting-cert
expected:
https://jpaztech.github.io/blog/network/appgw-troubleshooting-cert/

**Comment by juyamagu** [comment]
`hexo-generator-feed` は hexo の `url` と  `root` を考慮して feed を生成するようです。

https://github.com/hexojs/hexo-generator-feed/blob/c164383b6f08ae3051cbc8c09e22defe8c953a12/test/index.js#L33

```js
const urlConfigSubfolder = {
  // subdirectory configuration as per hexo documentation
  url: 'http://localhost/blog',
  root: '/blog/'
};
```

なので、`_config.yml` で以下の修正が必要と考えられます。

https://github.com/jpaztech/blog/blob/7d431cf7fbc474196bbc1839d513107a1066d1d0/_config.yml#L36

```diff
- url: https://jpaztech.github.io
+ url: https://jpaztech.github.io/blog
+ root: /blog/
```

**Comment by juyamagu** [comment]
@kiki-kekat どう思いますか?

**Comment by kiki-kekat** [comment]
url: https://jpaztech.github.io/blog/
root: /blog/

こうですかね。
皆さまありがとうございます。

**Comment by juyamagu** [comment]
https://jpaztech.github.io/blog/blog/atom.xml

![image](https://user-images.githubusercontent.com/52237425/84777455-94307d00-b01c-11ea-9da3-d4ff3c19dcf6.png)
