### ISSUE TITLE
画像のリンクが切れています

### ISSUE THREAD

**Issue by tsubasaxZZZ** [jpaztech/blog#63]
ExpressRoutePrefixRollout/ExpressRoutePrefixRollout1.png がないことが原因かと思います。

![image](https://user-images.githubusercontent.com/3822284/91528947-5b2d5680-e943-11ea-8fcf-7b9c54f75e9f.png)

---

#### Document Details

⚠ *Do not edit this section.

* ID: dab89d10-c6f2-5e1a-a3b7-7651a59d1594
* 対象記事: [ExpressRoute の Monthly Prefix Updates に関して](https://jpaztech.github.io/blog/network/ExpressRoutePrefixRollout/)
* Content Source: [articles/network/ExpressRoutePrefixRollout.md](https://github.com/jpaztech/blog/blob/master/articles/network/ExpressRoutePrefixRollout.md)
* Author:

**Comment by kiki-kekat** [comment]
大変失礼いたしました。修正いたしましたのでご確認ください。
